---
- name: Tareas Implementacion
  hosts: web
  tasks:

    - name: Crear archivo para almacenar resultados de las tareas Posteriores
      file:
        path: /tmp/parchado/tareas_previas.txt
        state: touch
    
    #Tareas Previas || Validacion de Kernel
        
    - name: Validacion de Kernel
      shell: |
         echo "Validacion de Kernel"
         uname -a
      register: kernel
    
    - name: Mostrar la validación del kernel
      debug:
            msg: "La validación del kernel es {{ kernel.stdout }}"
    
    - name: Guardar resultado de validación del kernel
      lineinfile:
              line: "{{ kernel.stdout }}"
              dest: /tmp/parchado/tareas_previas.txt
              insertafter: EOF
    
    #Tareas Previas || Validar fecha de ultimo reinicio
        
    - name: Validar fecha de ultimo reinicio
      shell: |
           echo "Validar fecha de ultimo reinicio"
           uptime
      register: uptime
    
    - name: Mostrar fecha de ultimo reinicio
      debug:
        msg: "La fecha de ultimo reinicio es {{ uptime.stdout }}"
        
    - name: Guardar resultado de validación de fecha de ultimo reinicio
      lineinfile:
            line: "{{ uptime.stdout }}"
            dest: /tmp/parchado/tareas_previas.txt
            insertafter: EOF

    - name: Crear archivo para almacenar resultados de las tareas de Implementacion
      file:
            path: /tmp/parchado/tareas_implementacion.txt
            state: touch

#Tareas Previas ||  Ejecutar instalación de parches de seguridad 

    - name: Ejecutar instalacion de parches de seguridad 
      shell: |
        echo " Ejecutando instalacion de parches de seguridad"
        sudo yum update --security -y
        yum update-minimal --security -y
      register: updateSecurity

    - name: Mostrar instalación de parches de seguridad 
      debug:
        msg: "La instalacion de parches de seguridad es {{ updateSecurity.stdout }}"
    
    - name: Guardar resultado de instalación de parches de seguridad
      lineinfile:
        line: "{{ updateSecurity.stdout }}"
        dest: /tmp/parchado/tareas_implementacion.txt
        insertafter: EOF
