---
- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
   become: yes
  hosts: web
  tasks:
- name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Aplicar actualizaciones
      apt:
        name: "*"
        state: latest

